Q3. Index of Pokédex

Problem Statement:

Given a 1D array, return the first and last elements from the array.
Input Format:

A 1D numpy array
Output Format:

A tuple (first_element, last_element)
Sample Input:

[0, 1, 2, 3, 4, 5]
Sample Output:

(0, 5)

In [14]:
import numpy as np

def get_elements(arr):
    '''
    INPUT: arr -> 1D numpy array
    
    OUTPUT elements -> tuple of first and last element.
    '''
    arr = np.array([24,25,26,27,27])
    
    first_element = arr[0]
    
    last_element = arr[-1]
    
    return (first_element, last_element)
  

get_elements(2)

(24, 27)

In [10]:
import numpy as np
    
data = np.array([0, 1, 2, 3, 4, 5])
    
first_element = data[0]
    
last_element = data[-1]

print("first_element:", first_element)
print("last_element:", last_element)

first_element: 0
last_element: 5


In [ ]:
# Correct Answer    
import numpy as np

def get_elements(arr):
    '''
    INPUT: arr -> 1D numpy array
    
    OUTPUT elements -> tuple of first and last element.
    '''
    array = np.array(arr)
    
    first_element = array[0]
    
    last_element = array[-1]
    
    return (first_element, last_element)

Q2 
a. Write the code using np.arange() to get all even numbers between 21 and 70, (70 inclusive)

b. Write the code using np.arange() to get all odd numbers between 20 and 71. (71 inclusive)

Which options correctly answer questions a and b?



In [36]:

import numpy as np
    
#data = np.arange(21,71)

#a1 = np.arange(20,72,2)
#print(a1)
#a2 = np.arrnag
#b = np.arrange(22,71,2)
#data1 = data %2== True 
#data2 = data %3== True
#print(b)
#print(data1)
#print(data2)

#first_element = data[0]
    
#last_element = data[-1]

#print("first_element:", first_element)
#print("last_element:", last_element)

a1 = np.arange(22,71,2)
print(a1)
a2 = np.arange(21,70,2)
print(a2)
b1 = np.arange(20,72,2)
print(b1)
b2 = np.arange(21,72,2)
print(b2)



[22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68
 70]
[21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55 57 59 61 63 65 67
 69]
[20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66
 68 70]
[21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55 57 59 61 63 65 67
 69 71]



Q2. Rotate the array
Unsolved
feature icon
Using hints except Complete Solution is Penalty free now
Use Hint
Given an array in form of a matrix of size (n, n), rotate the matrix clockwise by 90º.

Input Format:

A 2d numpy array
Output Format:

A 2d numpy array
Sample Input:

[[1 2 3] 
 [4 5 6]
 [7 8 9]]
Sample Output:

[[7 4 1]
 [8 5 2]
 [9 6 3]]

Note: Try Transpose / reversing.

In [96]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.rot90(arr,3))

[[7 4 1]
 [8 5 2]
 [9 6 3]]


In [105]:
# Trying with Transpose method
import numpy as np
def rotate_img(mat):
    '''mat -> A 2d numpy array
       output -> A 2d numpy array is expected to be returned'''
    arr1 = mat.T
    return arr1[:,::-1]

# Q4; Comparision Returns
a = np.array([100, 200, 300, 400])

b = np.array([300, 200, 100, 400])

print(a == b)

In [68]:
a = np.array([100, 200, 300, 400])

b = np.array([300, 200, 100, 400])

print(a == b)

[False  True False  True]


Q5. Cast a type
Unsolved
feature icon
Using hints except Complete Solution is Penalty free now
Use Hint
Raghu has created a numpy array arr using the following code:

import numpy as np
arr = np.array([10, 20, 30, 40, 50])
He wants to change the data type from integer to float.Which of the following is the correct approach to do so?

In [73]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])

#arr.astype('float64')

print(arr)



TypeError: only length-1 arrays can be converted to Python scalars

Q6. Transpose Reshaped
Unsolved
feature icon
Using hints except Complete Solution is Penalty free now
Use Hint
What would the following code print?

import numpy as np
a = np.array([[6, 28], [8, 56], [7, 19]])
x = np.transpose(a).reshape(1,6)
print(x)

In [74]:
import numpy as np
a = np.array([[6, 28], [8, 56], [7, 19]])
x = np.transpose(a).reshape(1,6)
print(x)

[[ 6  8  7 28 56 19]]


Q7. Distinction

You are given a numpy array containing marks of students in a class. The student gets distinction or first-division on the basis of the below criteria.

marks >= 80 : Distinction

60 <= marks < 80 : First Division

Find the ratio of number of students who got distinction to the number of students who got first division.

Sample Input-

array([20, 35, 68, 82, 83, 70, 90])
Sample Output-

1.5
Sample Explanation-

Distinction marks are 82, 83 and 90. So, 3 distinctions. First division marks are 68, 70. So 2 first divisions. Ratio = 3/2 = 1.5.

In [133]:
import numpy as np
def ratio(marks_arr):
    # Complete the missing code
    distinction = (marks_arr >= 80).sum() # Use masking to get the values
    first_div = np.ma(marks_arr<=60).sum() # Use masking to get the values
    
    distinction_count = len(distinction)
    first_div_count = len(first_div)
    
    ratio = distinction_count/first_div_count
    
    return round(ratio,2)

ratio([20, 35, 68, 82, 83, 70, 90])


TypeError: '>=' not supported between instances of 'list' and 'int'

In [136]:
import numpy as np
def ratio(marks_arr):
    # Complete the missing code
    distinction = (marks_arr >= 80).sum() # Use masking to get the values
    first_div = ((marks_arr >=60) & (marks_arr <80)).sum() # Use masking to get the values
    
    #distinction_count = len(distinction)
    #first_div_count = len(first_div)
    
    ratio = distinction/first_div
    
    return round(ratio,2)

In [122]:
#Mark the options which are true about the outputs for code snippets a and b.

#Code Snippet a:

import numpy as np
x = np.array([[200,200,200],[300,300,300],[400,400,400]])
v = np.array([200,300,400])
print((x / v[:,None])[1][1]) 

#Code Snippet b:

import numpy as np
p = np.array([[0], [10], [20]])
q = np.array([10, 11, 12]) 
print((p + q)[1][1]) 

1.0
21


'''Q2. Extract sub array

Problem Statement:

Given a 2d array, write a program to return a subarray such that the subarray consists of the elements from:

1. the second to the fourth row of the original array,

2. the elements in these rows should be from the last three columns of the corresponding rows of the original array,

3. the rows should be in reversed order.

Sample Input:
'''

[[ 0,  1,  2,  3],  
 [ 4,  5,  6,  7],   
 [ 8,  9, 10, 11],   
 [12, 13, 14, 15],   
 [16, 17, 18, 19]]

#Sample Output:

array([[13, 14, 15],  
       [ 9, 10, 11], 
       [ 5,  6,  7]])
#Input Format:

A 2D list
Output Format:

A 2D numpy array
Note:

This question can be solved using negative indexing and slicing

In [124]:
import numpy as np

def extract_subarray(arr):
    '''
    INPUT: arr -> 2D array
    
    OUPUT: result -> 2D array
    '''
    arr = np.array([[ 0,  1,  2,  3], [ 4,  5,  6,  7], [ 8,  9, 10, 11], [12, 13, 14, 15], [16, 17, 18, 19]])
    ### STEP1: Get the rows (2nd  to 4th row)
    
    row_array = arr[1:4]
    
    #### STEP 2: Get the last 3 cols from the row array
    
    cols_array = row_array[:,-3:]
    
    #### STEP3: Reverse the rows in cols array
    
    result = cols_array[::-1]
    

    return result

extract_subarray(arr)

array([[13, 14, 15],
       [ 9, 10, 11],
       [ 5,  6,  7]])

Q3. ORDER ORDER ORDER

Problem Statement:

Given a 2D numpy array, return array with its values in the column reversed.
Input Format:

A 2D numpy array
Output Format:

A 2D numpy array
Sample Input:

[[0, 1, 2], 
 [3, 4, 5], 
 [6, 7, 8]]
Sample Output:

[[2, 1, 0], 
 [5, 4, 3], 
 [8, 7, 6]]
P.S : Think about how we reverse list in python.

In [127]:
import numpy as np

def reverse_column(arr):
    '''
    INPUT: arr -> 2D array 
    
    OUTPUT rev_arr -> 2D array
    '''
    
    rev_arr = arr[::-1]
    
    return rev_arr

reverse_column(arr)

array([90, 70, 83, 82, 68, 35, 20])

Q4. Cast a type

Raghu has created a numpy array arr using the following code:

import numpy as np
arr = np.array([10, 20, 30, 40, 50])
He wants to change the data type from integer to float.Which of the following is the correct approach to do so?

In [131]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])

print(arr.astype('float64'))

[10. 20. 30. 40. 50.]


Q5. Batchmate's code

Your batchmate writes the following code :

import numpy as np
a = np.array([[16, 5], [81, 6], [33, 1]])
x=np.transpose(a).reshape(2,3)
print(x.flatten())
Which of the following is the correct output for the above code?

Note:

flatten() function is used to transform a multi-dimensional array into a one-dimensional array.
In other words, it "flattens" a multi-dimensional array structure into a simple linear sequence.

In [132]:
import numpy as np
a = np.array([[16, 5], [81, 6], [33, 1]])
x=np.transpose(a).reshape(2,3)
print(x.flatten())

[16 81 33  5  6  1]


Q6. Distinction
Unsolved
feature icon
Using hints except Complete Solution is Penalty free now
Use Hint
You are given a numpy array containing marks of students in a class. The student gets distinction or first-division on the basis of the below criteria.

marks >= 80 : Distinction

60 <= marks < 80 : First Division

Find the ratio of number of students who got distinction to the number of students who got first division.

Sample Input-

array([20, 35, 68, 82, 83, 70, 90])
Sample Output-

1.5
Sample Explanation-

Distinction marks are 82, 83 and 90. So, 3 distinctions. First division marks are 68, 70. So 2 first divisions. Ratio = 3/2 = 1.5.

###  Day 3
Q1. Matrix elements


    x = np.ones((5,5))
    x[1:-1,1:-1] = 0

In [144]:
x = np.ones((5,5))
print(x)
x[1:-1,1:-1] = 0
print("\n After calculation \n\n",x)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

 After calculation 

 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Q2. Comparing in numpy

a. What is the last element of the output?

    import numpy as np
    print(np.sort(np.array(['Ram','Astha','Raghavendra'])))

b. What is the output of the code snippet given below?

    arr1 = np.array(['Ram','Astha','Brahat'])
    arr2 = np.array(['Shyam','Kalyan','Naveen'])
    arr1 > arr2

Choose the options which are answers to questions a and b.

In [145]:
#Q2. Comparing in numpy
#Unsolved
#a. What is the last element of the output?

import numpy as np
print(np.sort(np.array(['Ram','Astha','Raghavendra'])))

#b. What is the output of the code snippet given below?


arr1 = np.array(['Ram','Astha','Brahat'])
arr2 = np.array(['Shyam','Kalyan','Naveen'])
arr1 > arr2
#Choose the options which are answers to questions a and b.

['Astha' 'Raghavendra' 'Ram']


array([False, False, False])

In [160]:
#Q3. Hstack
#Given the following array:

import numpy as np
arr = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])

print(arr)
#Which options are correct?

#a. np.hstack((arr, arr[:, 0])).shape = (3, 4)
a = np.hstack((arr, arr[:, [0]])).shape= (3, 4)
print("\n", a)

#np.hstack((arr,arr[:, 0]))

#Note: np is the alias for NumPy in the options.

[[1 2 3]
 [4 5 6]
 [7 8 9]]

 (3, 4)


Q4. Sort the birds

Given a list of birds and their corresponding age, return the name of birds sorted according to age (ascending)
Input Format:

Two 1D array list i.e. bird array and age array

Output Format:

A 1D array

Sample Input:

birds = ['spoonbills',  'plovers',  'plovers',  'plovers',  'plovers',  'Cranes',  'plovers',  'plovers',  'Cranes',  'spoonbills']

age = [5.5, 6.0, 3.5, 1.5, 3.0, 4.0, 3.5, 2.0, 5.5, 6.0]

Sample Output:

['plovers', 'plovers', 'plovers', 'plovers', 'plovers', 'Cranes', 'spoonbills', 'Cranes', 'plovers', 'spoonbills']

Side Note: Recall the functionality of .sort() and .argsort()

In [179]:
import numpy as np

def sort_birds(birds, age):
    '''
    INPUT: birds, age -> 1D numpy array
    
    OUTPUT: result -> sorted bird 1D array
    '''

    ## STEP 1 : Get the sorted index of age.
    
    sorted_age_index = np.argsort(age)
    
    ## STEP 2: Use the index from previous step to get sorted birds
    
    result = [birds[i] for i in sorted_age_index]
    
    return result

birds = ['spoonbills',  'plovers',  'plovers',  'plovers',  'plovers',  'Cranes',  'plovers',  'plovers',  'Cranes',  'spoonbills']
age = [5.5, 6.0, 3.5, 1.5, 3.0, 4.0, 3.5, 2.0, 5.5, 6.0]

sort_birds(birds,age)

['plovers',
 'plovers',
 'plovers',
 'plovers',
 'plovers',
 'Cranes',
 'spoonbills',
 'Cranes',
 'plovers',
 'spoonbills']

In [190]:
arr1 = np.array([1,2,3,6,3,2]) 
arr2 = np.array([4,2,1,3,3,2]) 
arr3 = np.zeros(len(arr1))

In [184]:
for i in range(len(arr1)): 
    arr3[i] = arr1[i] * arr2[i] 
    print(arr3[i])
    print(arr3)

4.0
[ 4.  4.  3. 18.  9.  4.]
4.0
[ 4.  4.  3. 18.  9.  4.]
3.0
[ 4.  4.  3. 18.  9.  4.]
18.0
[ 4.  4.  3. 18.  9.  4.]
9.0
[ 4.  4.  3. 18.  9.  4.]
4.0
[ 4.  4.  3. 18.  9.  4.]


In [186]:
arr3 = arr1*arr2 
print(arr3)

[ 4  4  3 18  9  4]


In [189]:
for i in range(len(arr1)): 
    if(arr1[i] < 0 ): 
        arr1[i] = -1 
    else: 
        arr1[i] = 1

print(arr1)
print(arr1[i])

[1 1 1 1 1 1]
1


In [191]:
np.where(arr1 > 0, 1, -1)

array([1, 1, 1, 1, 1, 1])

In [203]:
import numpy as np
arr = np.array([[[ 0, 1, 2],[ 3, 4, 5],[ 6, 7, 8]], [[ 9, 10, 11], [12, 13, 14],[15, 16, 17]]])

arr[:,:,1]

array([[ 1,  4,  7],
       [10, 13, 16]])

In [204]:
import numpy as np
a = np.arange(10,22).reshape((3, 4))
print(a)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [205]:
import numpy as np
arr= np.array([[2,3,4,5],[1,7,3,5],[2,8,6,9],[11,23,12,19]])

In [209]:
arr1 = np.array([[2,2,2,2]])
def func(x, y):
    return x * y
vec = np.vectorize(func)
vec(arr,arr1)

array([[ 4,  6,  8, 10],
       [ 2, 14,  6, 10],
       [ 4, 16, 12, 18],
       [22, 46, 24, 38]])

In [210]:
arr1 = np.array([[2],[2],[2],[2]])
def func(x, y):
    return x * y
vec = np.vectorize(func)
vec(arr, arr1)

array([[ 4,  6,  8, 10],
       [ 2, 14,  6, 10],
       [ 4, 16, 12, 18],
       [22, 46, 24, 38]])

In [211]:
arr1 = 2
def func(x, y):
    return x * y
vec = np.vectorize(func)
vec(arr, arr1)

array([[ 4,  6,  8, 10],
       [ 2, 14,  6, 10],
       [ 4, 16, 12, 18],
       [22, 46, 24, 38]])

Q2. Add padding

Given a NumPy array of shape (n,m). Add padding of a layer of 0’s on all 4 boundaries of the matrix.

Input Format:

First line will be consisting of two space-separated integers representing n and m.  
There will be n lines of input consisting of m space-separated integers representing the elements of rows of the array.

Output Format:

A 2d numpy array.
Sample Input:

3 2  
1 2  
3 4  
5 6

Sample Output:

[[0 0 0 0]
 [0 1 2 0]
 [0 3 4 0]
 [0 5 6 0]
 [0 0 0 0]]

In [241]:
import numpy as np
def add_padding(mat):
    '''mat-> NumPy array
       output-> NumPy array is expected to be returned'''

    # YOUR CODE GOES HERE
    arr1 = ([3,2],[1,2],[3,4],[5,6])
    #print(np.sort(arr1,axis=0))
    #arr2 = np.zeros((5,4))
    #print(arr2)
    pad_arr = np.pad(arr1,1,'constant',constant_values=0)
    print(pad_arr)
    res = None
    
    return res

add_padding(arr1)

[[0 0 0 0]
 [0 3 2 0]
 [0 1 2 0]
 [0 3 4 0]
 [0 5 6 0]
 [0 0 0 0]]


In [238]:
import numpy as np
def add_padding(mat):
    '''mat-> NumPy array
       output-> NumPy array is expected to be returned'''

    # YOUR CODE GOES HERE
    #np.sort(mat,axis=0)
    pad_arr = np.pad(mat,1,'constant',constant_values=0)
    res = pad_arr
    
    return res

Q3. Specific elements


Given two 2D arrays, row and column ranges,

Perform the following operations:

    Find the matrix multiplication of the given two matrices and
    Extract the elements from the output of above step using the given ranges
    If matrix multiplication is not possible, return -1
    Note: The end points (upper range) of both rows and columns are excluded.

Input Format:

There will be four lines of input as follows:  

- First line will have mat1.  
- Second line will have mat2.  
- Third line will have two space-separated integers representing start and end point of rows.  
- Fourth line will have two space-separated integers representing start and end point of columns.

Output Format:

A Numpy array
Sample Input:

[[6 6 4 7 9]  
 [0 2 2 9 3]  
 [6 0 2 5 2]  
 [2 4 3 5 5]]  
[[8 6 6 8 3]  
 [2 7 0 3 1]  
 [3 2 1 5 2]  
 [7 0 7 6 8]  
 [1 5 6 4 5]]  
1 3  
2 4
Sample Output:

[[83 82]  
 [85 96]]
Sample explanation:

The dimension of product is (5,5), and the elements for rows 1 to 4 and columns 2 to 4 are prd[1][2], prd[1][3], prd[2][2] and prd[2][3] i.e. 83, 82, 85 and 96.

In [307]:
import numpy as np
mat1=np.array([[6,6,4,7,9],[0,2,2,9,3],[6,0,2,5,2],[2,4,3,5,5]])
mat2=np.array([[8,6,6,8,3],[2,7,0,3,1],[3,2,1,5,2],[7,0,7,6,8],[1,5,6,4,5]])
def specific_elements(mat1,mat2):
    '''mat1,mat2 are the two 2d numpy array.
       r1,r2 are the start and end of rows indices
       c1,c2 are the start and end of columns indices
       Output = Return a numpy array according to indices'''

    # STEP1 CHECK whether matrix multiplication is possible
    
    if mat1.shape[1] != mat2.shape[0]:
       return -1
    
    
    ## STEP 2 Perform matrix multiplication
    matmul_array = np.dot(mat1, mat2)
    
    ## STEP 3 slice the array based on range value
    
   #result = mat
    
   #return 

specific_elements(mat1,mat2)


In [343]:
import numpy as np
mat1=np.array([[6,6,4,7,9],[0,2,2,9,3],[6,0,2,5,2],[2,4,3,5,5]])
mat2=np.array([[8,6,6,8,3],[2,7,0,3,1],[3,2,1,5,2],[7,0,7,6,8],[1,5,6,4,5]])


def func1():
   if mat1.shape[1] != mat2.shape[0]:
   #   notpos = print("notpossible")
      return "Notpossible"
   else:
      return "possible"

multmat = np.matmul(mat1,mat2)
multmat1 = np.dot(mat1,mat2)
print(multmat)
print (multmat1)
resu = matmult1[r1:r2,c1:c2]
print(resu)

func1()


[[130 131 143 164 133]
 [ 76  33  83  82  93]
 [ 91  50  85  96  72]
 [ 73  71  80  93  81]]
[[130 131 143 164 133]
 [ 76  33  83  82  93]
 [ 91  50  85  96  72]
 [ 73  71  80  93  81]]


NameError: name 'matmult1' is not defined

In [347]:
import numpy as np
def specific_elements(mat1,mat2,r1,r2,c1,c2):
    '''mat1,mat2 are the two 2d numpy array.
       r1,r2 are the start and end of rows indices
       c1,c2 are the start and end of columns indices
       Output = Return a numpy array according to indices'''
    
    # STEP1 CHECK whether matrix multiplication is possible
    
    if mat1.shape[1] == mat2.shape[0]:
        ## STEP 2 Perform matrix multiplication
        matmul_array = np.matmul(mat1,mat2)
        ## STEP 3 slice the array based on range value
        result = matmul_array[r1:r2, c1:c2]
        return result
    else:
        return -1

mat1=np.array([[6,6,4,7,9],[0,2,2,9,3],[6,0,2,5,2],[2,4,3,5,5]])
mat2=np.array([[8,6,6,8,3],[2,7,0,3,1],[3,2,1,5,2],[7,0,7,6,8],[1,5,6,4,5]])

specific_elements(mat1,mat2,1,3,2,4)
    

array([[83, 82],
       [85, 96]])

In [258]:
def greet(name):
    name = input(name)
    print("hello", name)
greet(name)

hello 123


In [251]:
greet(sathish)

NameError: name 'sathish' is not defined

Q4. Split and cycle

Using hints except Complete Solution is Penalty free now
Use Hint
You are given the following:

- A 2D Numpy array (data) representing a grayscale image, where pixel values range from 0 (black) to 255 (white).
- A desired number of horizontal splits (num_splits).

Tasks:

- Split the image to divide the image array (data) evenly into num_splits horizontal sections.
- Rearrange sections: Create a new array by concatenating the image sections in the following order:
    - The last section moves to the first position.
    - All other sections shift downwards by one position.
- Return the modified array

Input format:

    data: np.array
    num_splits: int

Output format:

    np.array
    Input Sample

data = np.array([[10, 20, 30],[40, 50, 60],[70, 80, 90],[100, 110, 120]])

num_splits = 2
Output Sample

[[ 70  80  90]
 [100 110 120]
 [ 10  20  30]
 [ 40  50  60]]

In [381]:
def rearrange_image(data, num_splits):
    data = np.array([[10, 20, 30],[40, 50, 60],[70, 80, 90],[100, 110, 120]])
    num_splits = 2 
    # write your code here
    print(data)
    data1= np.split(data,num_splits,axis=0)
    print("\n", data1)
    data2= np.concatenate(data1[-1:]+data1[:-1])
    print("\n",data2)
rearrange_image(data,2)

[[ 10  20  30]
 [ 40  50  60]
 [ 70  80  90]
 [100 110 120]]

 [array([[10, 20, 30],
       [40, 50, 60]]), array([[ 70,  80,  90],
       [100, 110, 120]])]

 [[ 70  80  90]
 [100 110 120]
 [ 10  20  30]
 [ 40  50  60]]


Q5. Oldest bird


Given a array of bird names and another array with corresponding ages of the birds, find the name of the oldest bird in the list.

Input Format:

Input has two lines.

- First line is the array of bird names (String).
- Second line is the array of ages of the birds (Int).

Output Format:

string

Sample Input:

    ['sparrow', 'peacock', 'parrot', 'owl', 'peacock', 'macaw', 'macaw', 'parrot', 'macaw', 'peacock']  
    [6, 1, 6, 5, 7, 6, 0, 9, 0, 7]

Sample Output:

parrot
Explanation:

parrot has age 9 which is the max of all the ages in the array; therefore parrot is returned.
Note:

Recall how to get index of maximum element

In [423]:
import numpy as np
birds=['sparrow', 'peacock', 'parrot', 'owl', 'peacock', 'macaw', 'macaw', 'parrot', 'macaw', 'peacock']  
birds_age=[6, 1, 6, 5, 7, 6, 0, 9, 0, 7]


def oldest_bird(birds, age):
    ''' birds[i] consist of the names of the type of ith bird
        age[i] consist of the age of ith bird'''
        
    ## STEP 1: Get the index of maximum age element
    
    max_age_index = age.index(max(age))
    
    
    ## STEP 2: Get the bird with maxium age using the above index
    
    old_bird = birds[max_age_index]
    
    
    return old_bird

oldest_bird(birds,birds_age)

'parrot'

Q6. Column split

Given an MxN 2D array (M >= 4),

Split the array column wise such that,

- 1st sub array contains the first 2 columns
- 2nd sub array contains the 3rd column
- 3rd sub array contains the rest of the columns

Input Format:

A 2D array

Output Format:

List of arrays
Sample Input:

[[0, 1, 2, 3],
 [4, 5, 6, 7],
 [8, 9, 10, 11],
 [12, 13, 14, 15],
 [16, 17, 18, 19],
 [20, 21, 22, 23]]

Sample Output:
[
array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13],
       [16, 17],
       [20, 21]]), 
array([[ 2],
       [ 6],
       [10],
       [14],
       [18],
       [22]]), 
array([[ 3],
       [ 7],
       [11],
       [15],
       [19],
       [23]])]
Output explanation:

Here, the first sub-array contains the first two columns of the input array.
Second sub-array contains the third column of the input array.
Third sub-array contains the rest of the columns, i.e the fourth column of the input array.

In [458]:
import numpy as np
arr=[[0, 1, 2, 3],[4, 5, 6, 7],[8, 9, 10, 11],[12, 13, 14, 15],[16, 17, 18, 19],[20, 21, 22, 23]]
def split1(arr):
    '''
    INPUT: arr -> 2D array
    
    OUTPUT: subarrays -> list of 2D arrays
    '''
    #arr=[[0, 1, 2, 3],[4, 5, 6, 7],[8, 9, 10, 11],[12, 13, 14, 15],[16, 17, 18, 19],[20, 21, 22, 23]]

    arr1=np.split(arr, [2,3], axis=1)
    #arr2=arr[]
    #arr3=arr[]
    
    subarrays = arr1
    ### CODE starts here 
    print(arr)

    return subarrays

split1(arr)

[[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11], [12, 13, 14, 15], [16, 17, 18, 19], [20, 21, 22, 23]]


[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13],
        [16, 17],
        [20, 21]]),
 array([[ 2],
        [ 6],
        [10],
        [14],
        [18],
        [22]]),
 array([[ 3],
        [ 7],
        [11],
        [15],
        [19],
        [23]])]

In [462]:
#help("keywords")
x = 5
id(x)

4383334288

In [463]:
print( not 2 < 4)

False


In [473]:
print(2 or 4)

2


In [489]:
print(6 % 20)

6


In [ ]:
Leap year? - III
Problem Description

Given an integer A representing a year, Return 1 if it is a leap year else, return 0.

A year is a leap year if the following conditions are satisfied:

The year is multiple of 400.
or the year is multiple of 4 and not multiple of 100.

Problem Constraints

1 <= A <= 109



Input Format

First and only argument is an integer A



Output Format

Return 1 if it is a leap year else return 0



Example Input

Input 1

 A = 2020
Input 2:

 A = 1999


Example Output

Output 1

 1
Output 2:

 0


Example Explanation

Explanation 1

 2020 is a leap year. 
 2020 is not a multiple of 400 but it is divisible by 4 and also at the same time not divisible by 100.
Explanation 2:

 1999 is not a leap year.
 199 is not a multiple of 400. It is not divisible by 4 and also at the same time not divisible by 100.
 All the conditions fail.



12345
class Solution:
    # @param A : integer
    # @return an integer
    def solve(self, A):

Output Result
theme-logo



In [505]:
class Solution:
    # @param A : integer
    # @return an integer
    def solve(self, A):
      A = input("Enter the input year")
      if (A % 400 ==0 ) and (A % 100 ==0 ):
         return 1
      else:
         return 0
    solve(self,A)

NameError: name 'self' is not defined

In [507]:
# Finding Unique list 
lst = [1,2,3,4,1,2,4]

In [515]:
def unique(li):
    newlist = []
    for i in li:
        if i not in newlist:
            newlist.append(i)
    return newlist 
unique(lst)


[1, 2, 3, 4]

In [516]:
l = [[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [534]:
l[2][1]

8

In [535]:
for i in l:
    print(i)

[1, 2, 3]
[4, 5, 6]
[7, 8, 9]


In [538]:
for i in l:
    for j in i:
        print(j)

1
2
3
4
5
6
7
8
9
